
package uk.ac.horizon.ug.exploding.client.model;
/** 
 * Identity element is ID.
 * 
 * Autogenerated by bean2java.xsl */
public class GameConfig
{

  /** no-arg cons */
  public GameConfig()
  {
  }

  /* implements ., i.e. 
    uk.ac.horizon.ug.exploding.db.GameConfig */
  
  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _ID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getID()
  {
  
    return _ID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setID(java.lang.String ID)
  {
  
    this._ID = ID;
    
  }

  /** is set?
   */
  public boolean isSetID() {
    return this._ID != null; 
  }

  /** unset
   */
  public void unsetID()  {
    this._ID = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _name;
  
  /** getter - 
   */
  public java.lang.String getName()
  {
  
    return _name;
    
  }

  /** setter - 
   */
  public void setName(java.lang.String name)
  {
  
    this._name = name;
    
  }

  /** is set?
   */
  public boolean isSetName() {
    return this._name != null; 
  }

  /** unset
   */
  public void unsetName()  {
    this._name = null; 
  }

  /** internal value - 
   */
  protected Float _spawnRadius;
  
  /** getter - 
   */
  public float getSpawnRadius()
  {
  
    // default value
    if (_spawnRadius==null)
      
        return 0;
         
    return _spawnRadius.floatValue();
    
  }

  /** setter - 
   */
  public void setSpawnRadius(float spawnRadius)
  {
  
    this._spawnRadius = new Float(spawnRadius);
    
  }

  /** is set?
   */
  public boolean isSetSpawnRadius() {
    return this._spawnRadius != null; 
  }

  /** unset
   */
  public void unsetSpawnRadius()  {
    this._spawnRadius = null; 
  }

  /** internal value - 
   */
  protected Float _proximityRadius;
  
  /** getter - 
   */
  public float getProximityRadius()
  {
  
    // default value
    if (_proximityRadius==null)
      
        return 0;
         
    return _proximityRadius.floatValue();
    
  }

  /** setter - 
   */
  public void setProximityRadius(float proximityRadius)
  {
  
    this._proximityRadius = new Float(proximityRadius);
    
  }

  /** is set?
   */
  public boolean isSetProximityRadius() {
    return this._proximityRadius != null; 
  }

  /** unset
   */
  public void unsetProximityRadius()  {
    this._proximityRadius = null; 
  }

  /** internal value - 
   */
  protected Integer _maxMembers;
  
  /** getter - 
   */
  public int getMaxMembers()
  {
  
    // default value
    if (_maxMembers==null)
      
        return 0;
         
    return _maxMembers.intValue();
    
  }

  /** setter - 
   */
  public void setMaxMembers(int maxMembers)
  {
  
    this._maxMembers = new Integer(maxMembers);
    
  }

  /** is set?
   */
  public boolean isSetMaxMembers() {
    return this._maxMembers != null; 
  }

  /** unset
   */
  public void unsetMaxMembers()  {
    this._maxMembers = null; 
  }

  /** internal value - 
   */
  protected Float _startTime;
  
  /** getter - 
   */
  public float getStartTime()
  {
  
    // default value
    if (_startTime==null)
      
        return 0;
         
    return _startTime.floatValue();
    
  }

  /** setter - 
   */
  public void setStartTime(float startTime)
  {
  
    this._startTime = new Float(startTime);
    
  }

  /** is set?
   */
  public boolean isSetStartTime() {
    return this._startTime != null; 
  }

  /** unset
   */
  public void unsetStartTime()  {
    this._startTime = null; 
  }

  /** internal value - 
   */
  protected Float _endTime;
  
  /** getter - 
   */
  public float getEndTime()
  {
  
    // default value
    if (_endTime==null)
      
        return 0;
         
    return _endTime.floatValue();
    
  }

  /** setter - 
   */
  public void setEndTime(float endTime)
  {
  
    this._endTime = new Float(endTime);
    
  }

  /** is set?
   */
  public boolean isSetEndTime() {
    return this._endTime != null; 
  }

  /** unset
   */
  public void unsetEndTime()  {
    this._endTime = null; 
  }

  /** internal value - 
   */
  protected Integer _enableDeath;
  
  /** getter - 
   */
  public int getEnableDeath()
  {
  
    // default value
    if (_enableDeath==null)
      
        return 0;
         
    return _enableDeath.intValue();
    
  }

  /** setter - 
   */
  public void setEnableDeath(int enableDeath)
  {
  
    this._enableDeath = new Integer(enableDeath);
    
  }

  /** is set?
   */
  public boolean isSetEnableDeath() {
    return this._enableDeath != null; 
  }

  /** unset
   */
  public void unsetEnableDeath()  {
    this._enableDeath = null; 
  }

  /** internal value - 
   */
  protected Integer _enableEventEffects;
  
  /** getter - 
   */
  public int getEnableEventEffects()
  {
  
    // default value
    if (_enableEventEffects==null)
      
        return 0;
         
    return _enableEventEffects.intValue();
    
  }

  /** setter - 
   */
  public void setEnableEventEffects(int enableEventEffects)
  {
  
    this._enableEventEffects = new Integer(enableEventEffects);
    
  }

  /** is set?
   */
  public boolean isSetEnableEventEffects() {
    return this._enableEventEffects != null; 
  }

  /** unset
   */
  public void unsetEnableEventEffects()  {
    this._enableEventEffects = null; 
  }

  /** internal value - 
   */
  protected Integer _enableSoleMemberZoneEffect;
  
  /** getter - 
   */
  public int getEnableSoleMemberZoneEffect()
  {
  
    // default value
    if (_enableSoleMemberZoneEffect==null)
      
        return 0;
         
    return _enableSoleMemberZoneEffect.intValue();
    
  }

  /** setter - 
   */
  public void setEnableSoleMemberZoneEffect(int enableSoleMemberZoneEffect)
  {
  
    this._enableSoleMemberZoneEffect = new Integer(enableSoleMemberZoneEffect);
    
  }

  /** is set?
   */
  public boolean isSetEnableSoleMemberZoneEffect() {
    return this._enableSoleMemberZoneEffect != null; 
  }

  /** unset
   */
  public void unsetEnableSoleMemberZoneEffect()  {
    this._enableSoleMemberZoneEffect = null; 
  }

  /** internal value - 
   */
  protected Integer _enableMultipleMemberZoneEffect;
  
  /** getter - 
   */
  public int getEnableMultipleMemberZoneEffect()
  {
  
    // default value
    if (_enableMultipleMemberZoneEffect==null)
      
        return 0;
         
    return _enableMultipleMemberZoneEffect.intValue();
    
  }

  /** setter - 
   */
  public void setEnableMultipleMemberZoneEffect(int enableMultipleMemberZoneEffect)
  {
  
    this._enableMultipleMemberZoneEffect = new Integer(enableMultipleMemberZoneEffect);
    
  }

  /** is set?
   */
  public boolean isSetEnableMultipleMemberZoneEffect() {
    return this._enableMultipleMemberZoneEffect != null; 
  }

  /** unset
   */
  public void unsetEnableMultipleMemberZoneEffect()  {
    this._enableMultipleMemberZoneEffect = null; 
  }

  /** internal value - 
   */
  protected Integer _enableAssimilation;
  
  /** getter - 
   */
  public int getEnableAssimilation()
  {
  
    // default value
    if (_enableAssimilation==null)
      
        return 0;
         
    return _enableAssimilation.intValue();
    
  }

  /** setter - 
   */
  public void setEnableAssimilation(int enableAssimilation)
  {
  
    this._enableAssimilation = new Integer(enableAssimilation);
    
  }

  /** is set?
   */
  public boolean isSetEnableAssimilation() {
    return this._enableAssimilation != null; 
  }

  /** unset
   */
  public void unsetEnableAssimilation()  {
    this._enableAssimilation = null; 
  }

  /** internal value - 
   */
  protected Integer _enableOffspring;
  
  /** getter - 
   */
  public int getEnableOffspring()
  {
  
    // default value
    if (_enableOffspring==null)
      
        return 0;
         
    return _enableOffspring.intValue();
    
  }

  /** setter - 
   */
  public void setEnableOffspring(int enableOffspring)
  {
  
    this._enableOffspring = new Integer(enableOffspring);
    
  }

  /** is set?
   */
  public boolean isSetEnableOffspring() {
    return this._enableOffspring != null; 
  }

  /** unset
   */
  public void unsetEnableOffspring()  {
    this._enableOffspring = null; 
  }

  /** internal value - 
   */
  protected Integer _enableAuthoring;
  
  /** getter - 
   */
  public int getEnableAuthoring()
  {
  
    // default value
    if (_enableAuthoring==null)
      
        return 0;
         
    return _enableAuthoring.intValue();
    
  }

  /** setter - 
   */
  public void setEnableAuthoring(int enableAuthoring)
  {
  
    this._enableAuthoring = new Integer(enableAuthoring);
    
  }

  /** is set?
   */
  public boolean isSetEnableAuthoring() {
    return this._enableAuthoring != null; 
  }

  /** unset
   */
  public void unsetEnableAuthoring()  {
    this._enableAuthoring = null; 
  }

  /** internal value - 
   */
  protected Integer _enableAuthoringQuota;
  
  /** getter - 
   */
  public int getEnableAuthoringQuota()
  {
  
    // default value
    if (_enableAuthoringQuota==null)
      
        return 0;
         
    return _enableAuthoringQuota.intValue();
    
  }

  /** setter - 
   */
  public void setEnableAuthoringQuota(int enableAuthoringQuota)
  {
  
    this._enableAuthoringQuota = new Integer(enableAuthoringQuota);
    
  }

  /** is set?
   */
  public boolean isSetEnableAuthoringQuota() {
    return this._enableAuthoringQuota != null; 
  }

  /** unset
   */
  public void unsetEnableAuthoringQuota()  {
    this._enableAuthoringQuota = null; 
  }

  /** internal value - 
   */
  protected Integer _enableMemberCreation;
  
  /** getter - 
   */
  public int getEnableMemberCreation()
  {
  
    // default value
    if (_enableMemberCreation==null)
      
        return 0;
         
    return _enableMemberCreation.intValue();
    
  }

  /** setter - 
   */
  public void setEnableMemberCreation(int enableMemberCreation)
  {
  
    this._enableMemberCreation = new Integer(enableMemberCreation);
    
  }

  /** is set?
   */
  public boolean isSetEnableMemberCreation() {
    return this._enableMemberCreation != null; 
  }

  /** unset
   */
  public void unsetEnableMemberCreation()  {
    this._enableMemberCreation = null; 
  }

  /** internal value - 
   */
  protected Integer _enableMemberQuota;
  
  /** getter - 
   */
  public int getEnableMemberQuota()
  {
  
    // default value
    if (_enableMemberQuota==null)
      
        return 0;
         
    return _enableMemberQuota.intValue();
    
  }

  /** setter - 
   */
  public void setEnableMemberQuota(int enableMemberQuota)
  {
  
    this._enableMemberQuota = new Integer(enableMemberQuota);
    
  }

  /** is set?
   */
  public boolean isSetEnableMemberQuota() {
    return this._enableMemberQuota != null; 
  }

  /** unset
   */
  public void unsetEnableMemberQuota()  {
    this._enableMemberQuota = null; 
  }

  /** internal value - 
   */
  protected Integer _initialMemberQuota;
  
  /** getter - 
   */
  public Integer getInitialMemberQuota()
  {
  
    return _initialMemberQuota;
    
  }

  /** setter - 
   */
  public void setInitialMemberQuota(Integer initialMemberQuota)
  {
  
    this._initialMemberQuota = initialMemberQuota;
    
  }

  /** is set?
   */
  public boolean isSetInitialMemberQuota() {
    return this._initialMemberQuota != null; 
  }

  /** unset
   */
  public void unsetInitialMemberQuota()  {
    this._initialMemberQuota = null; 
  }

  /** internal value - 
   */
  protected Integer _enableLocalMessagePriority;
  
  /** getter - 
   */
  public int getEnableLocalMessagePriority()
  {
  
    // default value
    if (_enableLocalMessagePriority==null)
      
        return 0;
         
    return _enableLocalMessagePriority.intValue();
    
  }

  /** setter - 
   */
  public void setEnableLocalMessagePriority(int enableLocalMessagePriority)
  {
  
    this._enableLocalMessagePriority = new Integer(enableLocalMessagePriority);
    
  }

  /** is set?
   */
  public boolean isSetEnableLocalMessagePriority() {
    return this._enableLocalMessagePriority != null; 
  }

  /** unset
   */
  public void unsetEnableLocalMessagePriority()  {
    this._enableLocalMessagePriority = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientCreateMinHealth;
  
  /** getter - 
   */
  public java.lang.Integer getClientCreateMinHealth()
  {
  
    return _clientCreateMinHealth;
    
  }

  /** setter - 
   */
  public void setClientCreateMinHealth(java.lang.Integer clientCreateMinHealth)
  {
  
    this._clientCreateMinHealth = clientCreateMinHealth;
    
  }

  /** is set?
   */
  public boolean isSetClientCreateMinHealth() {
    return this._clientCreateMinHealth != null; 
  }

  /** unset
   */
  public void unsetClientCreateMinHealth()  {
    this._clientCreateMinHealth = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientCreateMaxHealth;
  
  /** getter - 
   */
  public java.lang.Integer getClientCreateMaxHealth()
  {
  
    return _clientCreateMaxHealth;
    
  }

  /** setter - 
   */
  public void setClientCreateMaxHealth(java.lang.Integer clientCreateMaxHealth)
  {
  
    this._clientCreateMaxHealth = clientCreateMaxHealth;
    
  }

  /** is set?
   */
  public boolean isSetClientCreateMaxHealth() {
    return this._clientCreateMaxHealth != null; 
  }

  /** unset
   */
  public void unsetClientCreateMaxHealth()  {
    this._clientCreateMaxHealth = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientCreateMinWealth;
  
  /** getter - 
   */
  public java.lang.Integer getClientCreateMinWealth()
  {
  
    return _clientCreateMinWealth;
    
  }

  /** setter - 
   */
  public void setClientCreateMinWealth(java.lang.Integer clientCreateMinWealth)
  {
  
    this._clientCreateMinWealth = clientCreateMinWealth;
    
  }

  /** is set?
   */
  public boolean isSetClientCreateMinWealth() {
    return this._clientCreateMinWealth != null; 
  }

  /** unset
   */
  public void unsetClientCreateMinWealth()  {
    this._clientCreateMinWealth = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientCreateMaxWealth;
  
  /** getter - 
   */
  public java.lang.Integer getClientCreateMaxWealth()
  {
  
    return _clientCreateMaxWealth;
    
  }

  /** setter - 
   */
  public void setClientCreateMaxWealth(java.lang.Integer clientCreateMaxWealth)
  {
  
    this._clientCreateMaxWealth = clientCreateMaxWealth;
    
  }

  /** is set?
   */
  public boolean isSetClientCreateMaxWealth() {
    return this._clientCreateMaxWealth != null; 
  }

  /** unset
   */
  public void unsetClientCreateMaxWealth()  {
    this._clientCreateMaxWealth = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientCreateMinKnowledge;
  
  /** getter - 
   */
  public java.lang.Integer getClientCreateMinKnowledge()
  {
  
    return _clientCreateMinKnowledge;
    
  }

  /** setter - 
   */
  public void setClientCreateMinKnowledge(java.lang.Integer clientCreateMinKnowledge)
  {
  
    this._clientCreateMinKnowledge = clientCreateMinKnowledge;
    
  }

  /** is set?
   */
  public boolean isSetClientCreateMinKnowledge() {
    return this._clientCreateMinKnowledge != null; 
  }

  /** unset
   */
  public void unsetClientCreateMinKnowledge()  {
    this._clientCreateMinKnowledge = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientCreateMaxKnowledge;
  
  /** getter - 
   */
  public java.lang.Integer getClientCreateMaxKnowledge()
  {
  
    return _clientCreateMaxKnowledge;
    
  }

  /** setter - 
   */
  public void setClientCreateMaxKnowledge(java.lang.Integer clientCreateMaxKnowledge)
  {
  
    this._clientCreateMaxKnowledge = clientCreateMaxKnowledge;
    
  }

  /** is set?
   */
  public boolean isSetClientCreateMaxKnowledge() {
    return this._clientCreateMaxKnowledge != null; 
  }

  /** unset
   */
  public void unsetClientCreateMaxKnowledge()  {
    this._clientCreateMaxKnowledge = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientCreateMinParticipation;
  
  /** getter - 
   */
  public java.lang.Integer getClientCreateMinParticipation()
  {
  
    return _clientCreateMinParticipation;
    
  }

  /** setter - 
   */
  public void setClientCreateMinParticipation(java.lang.Integer clientCreateMinParticipation)
  {
  
    this._clientCreateMinParticipation = clientCreateMinParticipation;
    
  }

  /** is set?
   */
  public boolean isSetClientCreateMinParticipation() {
    return this._clientCreateMinParticipation != null; 
  }

  /** unset
   */
  public void unsetClientCreateMinParticipation()  {
    this._clientCreateMinParticipation = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientCreateMaxParticipation;
  
  /** getter - 
   */
  public java.lang.Integer getClientCreateMaxParticipation()
  {
  
    return _clientCreateMaxParticipation;
    
  }

  /** setter - 
   */
  public void setClientCreateMaxParticipation(java.lang.Integer clientCreateMaxParticipation)
  {
  
    this._clientCreateMaxParticipation = clientCreateMaxParticipation;
    
  }

  /** is set?
   */
  public boolean isSetClientCreateMaxParticipation() {
    return this._clientCreateMaxParticipation != null; 
  }

  /** unset
   */
  public void unsetClientCreateMaxParticipation()  {
    this._clientCreateMaxParticipation = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _clientMessageEndGame;
  
  /** getter - 
   */
  public java.lang.String getClientMessageEndGame()
  {
  
    return _clientMessageEndGame;
    
  }

  /** setter - 
   */
  public void setClientMessageEndGame(java.lang.String clientMessageEndGame)
  {
  
    this._clientMessageEndGame = clientMessageEndGame;
    
  }

  /** is set?
   */
  public boolean isSetClientMessageEndGame() {
    return this._clientMessageEndGame != null; 
  }

  /** unset
   */
  public void unsetClientMessageEndGame()  {
    this._clientMessageEndGame = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _clientMessageOutOfBounds;
  
  /** getter - 
   */
  public java.lang.String getClientMessageOutOfBounds()
  {
  
    return _clientMessageOutOfBounds;
    
  }

  /** setter - 
   */
  public void setClientMessageOutOfBounds(java.lang.String clientMessageOutOfBounds)
  {
  
    this._clientMessageOutOfBounds = clientMessageOutOfBounds;
    
  }

  /** is set?
   */
  public boolean isSetClientMessageOutOfBounds() {
    return this._clientMessageOutOfBounds != null; 
  }

  /** unset
   */
  public void unsetClientMessageOutOfBounds()  {
    this._clientMessageOutOfBounds = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientPollInterval;
  
  /** getter - 
   */
  public java.lang.Integer getClientPollInterval()
  {
  
    return _clientPollInterval;
    
  }

  /** setter - 
   */
  public void setClientPollInterval(java.lang.Integer clientPollInterval)
  {
  
    this._clientPollInterval = clientPollInterval;
    
  }

  /** is set?
   */
  public boolean isSetClientPollInterval() {
    return this._clientPollInterval != null; 
  }

  /** unset
   */
  public void unsetClientPollInterval()  {
    this._clientPollInterval = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientPollToFollow;
  
  /** getter - 
   */
  public java.lang.Integer getClientPollToFollow()
  {
  
    return _clientPollToFollow;
    
  }

  /** setter - 
   */
  public void setClientPollToFollow(java.lang.Integer clientPollToFollow)
  {
  
    this._clientPollToFollow = clientPollToFollow;
    
  }

  /** is set?
   */
  public boolean isSetClientPollToFollow() {
    return this._clientPollToFollow != null; 
  }

  /** unset
   */
  public void unsetClientPollToFollow()  {
    this._clientPollToFollow = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _clientHttpTimeout;
  
  /** getter - 
   */
  public java.lang.Integer getClientHttpTimeout()
  {
  
    return _clientHttpTimeout;
    
  }

  /** setter - 
   */
  public void setClientHttpTimeout(java.lang.Integer clientHttpTimeout)
  {
  
    this._clientHttpTimeout = clientHttpTimeout;
    
  }

  /** is set?
   */
  public boolean isSetClientHttpTimeout() {
    return this._clientHttpTimeout != null; 
  }

  /** unset
   */
  public void unsetClientHttpTimeout()  {
    this._clientHttpTimeout = null; 
  }

  /** internal value - 
   */
  protected java.lang.Boolean _clientShowZonesOnMap;
  
  /** getter - 
   */
  public java.lang.Boolean getClientShowZonesOnMap()
  {
  
    return _clientShowZonesOnMap;
    
  }

  /** setter - 
   */
  public void setClientShowZonesOnMap(java.lang.Boolean clientShowZonesOnMap)
  {
  
    this._clientShowZonesOnMap = clientShowZonesOnMap;
    
  }

  /** is set?
   */
  public boolean isSetClientShowZonesOnMap() {
    return this._clientShowZonesOnMap != null; 
  }

  /** unset
   */
  public void unsetClientShowZonesOnMap()  {
    this._clientShowZonesOnMap = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgAssimilated;
  
  /** getter - 
   */
  public java.lang.String getContextMsgAssimilated()
  {
  
    return _contextMsgAssimilated;
    
  }

  /** setter - 
   */
  public void setContextMsgAssimilated(java.lang.String contextMsgAssimilated)
  {
  
    this._contextMsgAssimilated = contextMsgAssimilated;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgAssimilated() {
    return this._contextMsgAssimilated != null; 
  }

  /** unset
   */
  public void unsetContextMsgAssimilated()  {
    this._contextMsgAssimilated = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgAssimilatedTitle;
  
  /** getter - 
   */
  public java.lang.String getContextMsgAssimilatedTitle()
  {
  
    return _contextMsgAssimilatedTitle;
    
  }

  /** setter - 
   */
  public void setContextMsgAssimilatedTitle(java.lang.String contextMsgAssimilatedTitle)
  {
  
    this._contextMsgAssimilatedTitle = contextMsgAssimilatedTitle;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgAssimilatedTitle() {
    return this._contextMsgAssimilatedTitle != null; 
  }

  /** unset
   */
  public void unsetContextMsgAssimilatedTitle()  {
    this._contextMsgAssimilatedTitle = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgAssimilate;
  
  /** getter - 
   */
  public java.lang.String getContextMsgAssimilate()
  {
  
    return _contextMsgAssimilate;
    
  }

  /** setter - 
   */
  public void setContextMsgAssimilate(java.lang.String contextMsgAssimilate)
  {
  
    this._contextMsgAssimilate = contextMsgAssimilate;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgAssimilate() {
    return this._contextMsgAssimilate != null; 
  }

  /** unset
   */
  public void unsetContextMsgAssimilate()  {
    this._contextMsgAssimilate = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgAssimilateTitle;
  
  /** getter - 
   */
  public java.lang.String getContextMsgAssimilateTitle()
  {
  
    return _contextMsgAssimilateTitle;
    
  }

  /** setter - 
   */
  public void setContextMsgAssimilateTitle(java.lang.String contextMsgAssimilateTitle)
  {
  
    this._contextMsgAssimilateTitle = contextMsgAssimilateTitle;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgAssimilateTitle() {
    return this._contextMsgAssimilateTitle != null; 
  }

  /** unset
   */
  public void unsetContextMsgAssimilateTitle()  {
    this._contextMsgAssimilateTitle = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgBirth;
  
  /** getter - 
   */
  public java.lang.String getContextMsgBirth()
  {
  
    return _contextMsgBirth;
    
  }

  /** setter - 
   */
  public void setContextMsgBirth(java.lang.String contextMsgBirth)
  {
  
    this._contextMsgBirth = contextMsgBirth;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgBirth() {
    return this._contextMsgBirth != null; 
  }

  /** unset
   */
  public void unsetContextMsgBirth()  {
    this._contextMsgBirth = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgBirthTitle;
  
  /** getter - 
   */
  public java.lang.String getContextMsgBirthTitle()
  {
  
    return _contextMsgBirthTitle;
    
  }

  /** setter - 
   */
  public void setContextMsgBirthTitle(java.lang.String contextMsgBirthTitle)
  {
  
    this._contextMsgBirthTitle = contextMsgBirthTitle;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgBirthTitle() {
    return this._contextMsgBirthTitle != null; 
  }

  /** unset
   */
  public void unsetContextMsgBirthTitle()  {
    this._contextMsgBirthTitle = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgDeath;
  
  /** getter - 
   */
  public java.lang.String getContextMsgDeath()
  {
  
    return _contextMsgDeath;
    
  }

  /** setter - 
   */
  public void setContextMsgDeath(java.lang.String contextMsgDeath)
  {
  
    this._contextMsgDeath = contextMsgDeath;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgDeath() {
    return this._contextMsgDeath != null; 
  }

  /** unset
   */
  public void unsetContextMsgDeath()  {
    this._contextMsgDeath = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgDeathTitle;
  
  /** getter - 
   */
  public java.lang.String getContextMsgDeathTitle()
  {
  
    return _contextMsgDeathTitle;
    
  }

  /** setter - 
   */
  public void setContextMsgDeathTitle(java.lang.String contextMsgDeathTitle)
  {
  
    this._contextMsgDeathTitle = contextMsgDeathTitle;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgDeathTitle() {
    return this._contextMsgDeathTitle != null; 
  }

  /** unset
   */
  public void unsetContextMsgDeathTitle()  {
    this._contextMsgDeathTitle = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgEnd;
  
  /** getter - 
   */
  public java.lang.String getContextMsgEnd()
  {
  
    return _contextMsgEnd;
    
  }

  /** setter - 
   */
  public void setContextMsgEnd(java.lang.String contextMsgEnd)
  {
  
    this._contextMsgEnd = contextMsgEnd;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgEnd() {
    return this._contextMsgEnd != null; 
  }

  /** unset
   */
  public void unsetContextMsgEnd()  {
    this._contextMsgEnd = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgEndTitle;
  
  /** getter - 
   */
  public java.lang.String getContextMsgEndTitle()
  {
  
    return _contextMsgEndTitle;
    
  }

  /** setter - 
   */
  public void setContextMsgEndTitle(java.lang.String contextMsgEndTitle)
  {
  
    this._contextMsgEndTitle = contextMsgEndTitle;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgEndTitle() {
    return this._contextMsgEndTitle != null; 
  }

  /** unset
   */
  public void unsetContextMsgEndTitle()  {
    this._contextMsgEndTitle = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgScare;
  
  /** getter - 
   */
  public java.lang.String getContextMsgScare()
  {
  
    return _contextMsgScare;
    
  }

  /** setter - 
   */
  public void setContextMsgScare(java.lang.String contextMsgScare)
  {
  
    this._contextMsgScare = contextMsgScare;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgScare() {
    return this._contextMsgScare != null; 
  }

  /** unset
   */
  public void unsetContextMsgScare()  {
    this._contextMsgScare = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _contextMsgScareTitle;
  
  /** getter - 
   */
  public java.lang.String getContextMsgScareTitle()
  {
  
    return _contextMsgScareTitle;
    
  }

  /** setter - 
   */
  public void setContextMsgScareTitle(java.lang.String contextMsgScareTitle)
  {
  
    this._contextMsgScareTitle = contextMsgScareTitle;
    
  }

  /** is set?
   */
  public boolean isSetContextMsgScareTitle() {
    return this._contextMsgScareTitle != null; 
  }

  /** unset
   */
  public void unsetContextMsgScareTitle()  {
    this._contextMsgScareTitle = null; 
  }

  /** equals */
  public boolean equals(Object o) {
    if (o==null) return false;
    if (!(o instanceof GameConfig)) return false;
    GameConfig oo = (GameConfig)o;
      if (_ID!=oo._ID &&
        (_ID==null || oo._ID==null ||
         !_ID.equals(oo._ID)))
      return false;
    if (_name!=oo._name &&
        (_name==null || oo._name==null ||
         !_name.equals(oo._name)))
      return false;
    if (_spawnRadius!=oo._spawnRadius &&
        (_spawnRadius==null || oo._spawnRadius==null ||
         !_spawnRadius.equals(oo._spawnRadius)))
      return false;
    if (_proximityRadius!=oo._proximityRadius &&
        (_proximityRadius==null || oo._proximityRadius==null ||
         !_proximityRadius.equals(oo._proximityRadius)))
      return false;
    if (_maxMembers!=oo._maxMembers &&
        (_maxMembers==null || oo._maxMembers==null ||
         !_maxMembers.equals(oo._maxMembers)))
      return false;
    if (_startTime!=oo._startTime &&
        (_startTime==null || oo._startTime==null ||
         !_startTime.equals(oo._startTime)))
      return false;
    if (_endTime!=oo._endTime &&
        (_endTime==null || oo._endTime==null ||
         !_endTime.equals(oo._endTime)))
      return false;
    if (_enableDeath!=oo._enableDeath &&
        (_enableDeath==null || oo._enableDeath==null ||
         !_enableDeath.equals(oo._enableDeath)))
      return false;
    if (_enableEventEffects!=oo._enableEventEffects &&
        (_enableEventEffects==null || oo._enableEventEffects==null ||
         !_enableEventEffects.equals(oo._enableEventEffects)))
      return false;
    if (_enableSoleMemberZoneEffect!=oo._enableSoleMemberZoneEffect &&
        (_enableSoleMemberZoneEffect==null || oo._enableSoleMemberZoneEffect==null ||
         !_enableSoleMemberZoneEffect.equals(oo._enableSoleMemberZoneEffect)))
      return false;
    if (_enableMultipleMemberZoneEffect!=oo._enableMultipleMemberZoneEffect &&
        (_enableMultipleMemberZoneEffect==null || oo._enableMultipleMemberZoneEffect==null ||
         !_enableMultipleMemberZoneEffect.equals(oo._enableMultipleMemberZoneEffect)))
      return false;
    if (_enableAssimilation!=oo._enableAssimilation &&
        (_enableAssimilation==null || oo._enableAssimilation==null ||
         !_enableAssimilation.equals(oo._enableAssimilation)))
      return false;
    if (_enableOffspring!=oo._enableOffspring &&
        (_enableOffspring==null || oo._enableOffspring==null ||
         !_enableOffspring.equals(oo._enableOffspring)))
      return false;
    if (_enableAuthoring!=oo._enableAuthoring &&
        (_enableAuthoring==null || oo._enableAuthoring==null ||
         !_enableAuthoring.equals(oo._enableAuthoring)))
      return false;
    if (_enableAuthoringQuota!=oo._enableAuthoringQuota &&
        (_enableAuthoringQuota==null || oo._enableAuthoringQuota==null ||
         !_enableAuthoringQuota.equals(oo._enableAuthoringQuota)))
      return false;
    if (_enableMemberCreation!=oo._enableMemberCreation &&
        (_enableMemberCreation==null || oo._enableMemberCreation==null ||
         !_enableMemberCreation.equals(oo._enableMemberCreation)))
      return false;
    if (_enableMemberQuota!=oo._enableMemberQuota &&
        (_enableMemberQuota==null || oo._enableMemberQuota==null ||
         !_enableMemberQuota.equals(oo._enableMemberQuota)))
      return false;
    if (_initialMemberQuota!=oo._initialMemberQuota &&
        (_initialMemberQuota==null || oo._initialMemberQuota==null ||
         !_initialMemberQuota.equals(oo._initialMemberQuota)))
      return false;
    if (_enableLocalMessagePriority!=oo._enableLocalMessagePriority &&
        (_enableLocalMessagePriority==null || oo._enableLocalMessagePriority==null ||
         !_enableLocalMessagePriority.equals(oo._enableLocalMessagePriority)))
      return false;
    if (_clientCreateMinHealth!=oo._clientCreateMinHealth &&
        (_clientCreateMinHealth==null || oo._clientCreateMinHealth==null ||
         !_clientCreateMinHealth.equals(oo._clientCreateMinHealth)))
      return false;
    if (_clientCreateMaxHealth!=oo._clientCreateMaxHealth &&
        (_clientCreateMaxHealth==null || oo._clientCreateMaxHealth==null ||
         !_clientCreateMaxHealth.equals(oo._clientCreateMaxHealth)))
      return false;
    if (_clientCreateMinWealth!=oo._clientCreateMinWealth &&
        (_clientCreateMinWealth==null || oo._clientCreateMinWealth==null ||
         !_clientCreateMinWealth.equals(oo._clientCreateMinWealth)))
      return false;
    if (_clientCreateMaxWealth!=oo._clientCreateMaxWealth &&
        (_clientCreateMaxWealth==null || oo._clientCreateMaxWealth==null ||
         !_clientCreateMaxWealth.equals(oo._clientCreateMaxWealth)))
      return false;
    if (_clientCreateMinKnowledge!=oo._clientCreateMinKnowledge &&
        (_clientCreateMinKnowledge==null || oo._clientCreateMinKnowledge==null ||
         !_clientCreateMinKnowledge.equals(oo._clientCreateMinKnowledge)))
      return false;
    if (_clientCreateMaxKnowledge!=oo._clientCreateMaxKnowledge &&
        (_clientCreateMaxKnowledge==null || oo._clientCreateMaxKnowledge==null ||
         !_clientCreateMaxKnowledge.equals(oo._clientCreateMaxKnowledge)))
      return false;
    if (_clientCreateMinParticipation!=oo._clientCreateMinParticipation &&
        (_clientCreateMinParticipation==null || oo._clientCreateMinParticipation==null ||
         !_clientCreateMinParticipation.equals(oo._clientCreateMinParticipation)))
      return false;
    if (_clientCreateMaxParticipation!=oo._clientCreateMaxParticipation &&
        (_clientCreateMaxParticipation==null || oo._clientCreateMaxParticipation==null ||
         !_clientCreateMaxParticipation.equals(oo._clientCreateMaxParticipation)))
      return false;
    if (_clientMessageEndGame!=oo._clientMessageEndGame &&
        (_clientMessageEndGame==null || oo._clientMessageEndGame==null ||
         !_clientMessageEndGame.equals(oo._clientMessageEndGame)))
      return false;
    if (_clientMessageOutOfBounds!=oo._clientMessageOutOfBounds &&
        (_clientMessageOutOfBounds==null || oo._clientMessageOutOfBounds==null ||
         !_clientMessageOutOfBounds.equals(oo._clientMessageOutOfBounds)))
      return false;
    if (_clientPollInterval!=oo._clientPollInterval &&
        (_clientPollInterval==null || oo._clientPollInterval==null ||
         !_clientPollInterval.equals(oo._clientPollInterval)))
      return false;
    if (_clientPollToFollow!=oo._clientPollToFollow &&
        (_clientPollToFollow==null || oo._clientPollToFollow==null ||
         !_clientPollToFollow.equals(oo._clientPollToFollow)))
      return false;
    if (_clientHttpTimeout!=oo._clientHttpTimeout &&
        (_clientHttpTimeout==null || oo._clientHttpTimeout==null ||
         !_clientHttpTimeout.equals(oo._clientHttpTimeout)))
      return false;
    if (_clientShowZonesOnMap!=oo._clientShowZonesOnMap &&
        (_clientShowZonesOnMap==null || oo._clientShowZonesOnMap==null ||
         !_clientShowZonesOnMap.equals(oo._clientShowZonesOnMap)))
      return false;
    if (_contextMsgAssimilated!=oo._contextMsgAssimilated &&
        (_contextMsgAssimilated==null || oo._contextMsgAssimilated==null ||
         !_contextMsgAssimilated.equals(oo._contextMsgAssimilated)))
      return false;
    if (_contextMsgAssimilatedTitle!=oo._contextMsgAssimilatedTitle &&
        (_contextMsgAssimilatedTitle==null || oo._contextMsgAssimilatedTitle==null ||
         !_contextMsgAssimilatedTitle.equals(oo._contextMsgAssimilatedTitle)))
      return false;
    if (_contextMsgAssimilate!=oo._contextMsgAssimilate &&
        (_contextMsgAssimilate==null || oo._contextMsgAssimilate==null ||
         !_contextMsgAssimilate.equals(oo._contextMsgAssimilate)))
      return false;
    if (_contextMsgAssimilateTitle!=oo._contextMsgAssimilateTitle &&
        (_contextMsgAssimilateTitle==null || oo._contextMsgAssimilateTitle==null ||
         !_contextMsgAssimilateTitle.equals(oo._contextMsgAssimilateTitle)))
      return false;
    if (_contextMsgBirth!=oo._contextMsgBirth &&
        (_contextMsgBirth==null || oo._contextMsgBirth==null ||
         !_contextMsgBirth.equals(oo._contextMsgBirth)))
      return false;
    if (_contextMsgBirthTitle!=oo._contextMsgBirthTitle &&
        (_contextMsgBirthTitle==null || oo._contextMsgBirthTitle==null ||
         !_contextMsgBirthTitle.equals(oo._contextMsgBirthTitle)))
      return false;
    if (_contextMsgDeath!=oo._contextMsgDeath &&
        (_contextMsgDeath==null || oo._contextMsgDeath==null ||
         !_contextMsgDeath.equals(oo._contextMsgDeath)))
      return false;
    if (_contextMsgDeathTitle!=oo._contextMsgDeathTitle &&
        (_contextMsgDeathTitle==null || oo._contextMsgDeathTitle==null ||
         !_contextMsgDeathTitle.equals(oo._contextMsgDeathTitle)))
      return false;
    if (_contextMsgEnd!=oo._contextMsgEnd &&
        (_contextMsgEnd==null || oo._contextMsgEnd==null ||
         !_contextMsgEnd.equals(oo._contextMsgEnd)))
      return false;
    if (_contextMsgEndTitle!=oo._contextMsgEndTitle &&
        (_contextMsgEndTitle==null || oo._contextMsgEndTitle==null ||
         !_contextMsgEndTitle.equals(oo._contextMsgEndTitle)))
      return false;
    if (_contextMsgScare!=oo._contextMsgScare &&
        (_contextMsgScare==null || oo._contextMsgScare==null ||
         !_contextMsgScare.equals(oo._contextMsgScare)))
      return false;
    if (_contextMsgScareTitle!=oo._contextMsgScareTitle &&
        (_contextMsgScareTitle==null || oo._contextMsgScareTitle==null ||
         !_contextMsgScareTitle.equals(oo._contextMsgScareTitle)))
      return false;

    return true;
  }
  /** hashcode */
  public int hashCode() {
    int val = 0;
      if (_ID!=null) val = val ^ _ID.hashCode();
    if (_name!=null) val = val ^ _name.hashCode();
    if (_spawnRadius!=null) val = val ^ _spawnRadius.hashCode();
    if (_proximityRadius!=null) val = val ^ _proximityRadius.hashCode();
    if (_maxMembers!=null) val = val ^ _maxMembers.hashCode();
    if (_startTime!=null) val = val ^ _startTime.hashCode();
    if (_endTime!=null) val = val ^ _endTime.hashCode();
    if (_enableDeath!=null) val = val ^ _enableDeath.hashCode();
    if (_enableEventEffects!=null) val = val ^ _enableEventEffects.hashCode();
    if (_enableSoleMemberZoneEffect!=null) val = val ^ _enableSoleMemberZoneEffect.hashCode();
    if (_enableMultipleMemberZoneEffect!=null) val = val ^ _enableMultipleMemberZoneEffect.hashCode();
    if (_enableAssimilation!=null) val = val ^ _enableAssimilation.hashCode();
    if (_enableOffspring!=null) val = val ^ _enableOffspring.hashCode();
    if (_enableAuthoring!=null) val = val ^ _enableAuthoring.hashCode();
    if (_enableAuthoringQuota!=null) val = val ^ _enableAuthoringQuota.hashCode();
    if (_enableMemberCreation!=null) val = val ^ _enableMemberCreation.hashCode();
    if (_enableMemberQuota!=null) val = val ^ _enableMemberQuota.hashCode();
    if (_initialMemberQuota!=null) val = val ^ _initialMemberQuota.hashCode();
    if (_enableLocalMessagePriority!=null) val = val ^ _enableLocalMessagePriority.hashCode();
    if (_clientCreateMinHealth!=null) val = val ^ _clientCreateMinHealth.hashCode();
    if (_clientCreateMaxHealth!=null) val = val ^ _clientCreateMaxHealth.hashCode();
    if (_clientCreateMinWealth!=null) val = val ^ _clientCreateMinWealth.hashCode();
    if (_clientCreateMaxWealth!=null) val = val ^ _clientCreateMaxWealth.hashCode();
    if (_clientCreateMinKnowledge!=null) val = val ^ _clientCreateMinKnowledge.hashCode();
    if (_clientCreateMaxKnowledge!=null) val = val ^ _clientCreateMaxKnowledge.hashCode();
    if (_clientCreateMinParticipation!=null) val = val ^ _clientCreateMinParticipation.hashCode();
    if (_clientCreateMaxParticipation!=null) val = val ^ _clientCreateMaxParticipation.hashCode();
    if (_clientMessageEndGame!=null) val = val ^ _clientMessageEndGame.hashCode();
    if (_clientMessageOutOfBounds!=null) val = val ^ _clientMessageOutOfBounds.hashCode();
    if (_clientPollInterval!=null) val = val ^ _clientPollInterval.hashCode();
    if (_clientPollToFollow!=null) val = val ^ _clientPollToFollow.hashCode();
    if (_clientHttpTimeout!=null) val = val ^ _clientHttpTimeout.hashCode();
    if (_clientShowZonesOnMap!=null) val = val ^ _clientShowZonesOnMap.hashCode();
    if (_contextMsgAssimilated!=null) val = val ^ _contextMsgAssimilated.hashCode();
    if (_contextMsgAssimilatedTitle!=null) val = val ^ _contextMsgAssimilatedTitle.hashCode();
    if (_contextMsgAssimilate!=null) val = val ^ _contextMsgAssimilate.hashCode();
    if (_contextMsgAssimilateTitle!=null) val = val ^ _contextMsgAssimilateTitle.hashCode();
    if (_contextMsgBirth!=null) val = val ^ _contextMsgBirth.hashCode();
    if (_contextMsgBirthTitle!=null) val = val ^ _contextMsgBirthTitle.hashCode();
    if (_contextMsgDeath!=null) val = val ^ _contextMsgDeath.hashCode();
    if (_contextMsgDeathTitle!=null) val = val ^ _contextMsgDeathTitle.hashCode();
    if (_contextMsgEnd!=null) val = val ^ _contextMsgEnd.hashCode();
    if (_contextMsgEndTitle!=null) val = val ^ _contextMsgEndTitle.hashCode();
    if (_contextMsgScare!=null) val = val ^ _contextMsgScare.hashCode();
    if (_contextMsgScareTitle!=null) val = val ^ _contextMsgScareTitle.hashCode();

    return val;
  }
  /** tostring */
  public String toString() {
    StringBuilder str = new StringBuilder("GameConfig:");
    
    str.append("{");
    
    
	str.append("ID=");
	if (_ID!=null) {
	    str.append(_ID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("name=");
	if (_name!=null) {
	    str.append(_name.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("spawnRadius=");
	if (_spawnRadius!=null) {
	    str.append(_spawnRadius.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("proximityRadius=");
	if (_proximityRadius!=null) {
	    str.append(_proximityRadius.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("maxMembers=");
	if (_maxMembers!=null) {
	    str.append(_maxMembers.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("startTime=");
	if (_startTime!=null) {
	    str.append(_startTime.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("endTime=");
	if (_endTime!=null) {
	    str.append(_endTime.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableDeath=");
	if (_enableDeath!=null) {
	    str.append(_enableDeath.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableEventEffects=");
	if (_enableEventEffects!=null) {
	    str.append(_enableEventEffects.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableSoleMemberZoneEffect=");
	if (_enableSoleMemberZoneEffect!=null) {
	    str.append(_enableSoleMemberZoneEffect.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableMultipleMemberZoneEffect=");
	if (_enableMultipleMemberZoneEffect!=null) {
	    str.append(_enableMultipleMemberZoneEffect.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableAssimilation=");
	if (_enableAssimilation!=null) {
	    str.append(_enableAssimilation.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableOffspring=");
	if (_enableOffspring!=null) {
	    str.append(_enableOffspring.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableAuthoring=");
	if (_enableAuthoring!=null) {
	    str.append(_enableAuthoring.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableAuthoringQuota=");
	if (_enableAuthoringQuota!=null) {
	    str.append(_enableAuthoringQuota.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableMemberCreation=");
	if (_enableMemberCreation!=null) {
	    str.append(_enableMemberCreation.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableMemberQuota=");
	if (_enableMemberQuota!=null) {
	    str.append(_enableMemberQuota.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("initialMemberQuota=");
	if (_initialMemberQuota!=null) {
	    str.append(_initialMemberQuota.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enableLocalMessagePriority=");
	if (_enableLocalMessagePriority!=null) {
	    str.append(_enableLocalMessagePriority.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientCreateMinHealth=");
	if (_clientCreateMinHealth!=null) {
	    str.append(_clientCreateMinHealth.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientCreateMaxHealth=");
	if (_clientCreateMaxHealth!=null) {
	    str.append(_clientCreateMaxHealth.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientCreateMinWealth=");
	if (_clientCreateMinWealth!=null) {
	    str.append(_clientCreateMinWealth.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientCreateMaxWealth=");
	if (_clientCreateMaxWealth!=null) {
	    str.append(_clientCreateMaxWealth.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientCreateMinKnowledge=");
	if (_clientCreateMinKnowledge!=null) {
	    str.append(_clientCreateMinKnowledge.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientCreateMaxKnowledge=");
	if (_clientCreateMaxKnowledge!=null) {
	    str.append(_clientCreateMaxKnowledge.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientCreateMinParticipation=");
	if (_clientCreateMinParticipation!=null) {
	    str.append(_clientCreateMinParticipation.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientCreateMaxParticipation=");
	if (_clientCreateMaxParticipation!=null) {
	    str.append(_clientCreateMaxParticipation.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientMessageEndGame=");
	if (_clientMessageEndGame!=null) {
	    str.append(_clientMessageEndGame.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientMessageOutOfBounds=");
	if (_clientMessageOutOfBounds!=null) {
	    str.append(_clientMessageOutOfBounds.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientPollInterval=");
	if (_clientPollInterval!=null) {
	    str.append(_clientPollInterval.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientPollToFollow=");
	if (_clientPollToFollow!=null) {
	    str.append(_clientPollToFollow.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientHttpTimeout=");
	if (_clientHttpTimeout!=null) {
	    str.append(_clientHttpTimeout.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("clientShowZonesOnMap=");
	if (_clientShowZonesOnMap!=null) {
	    str.append(_clientShowZonesOnMap.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgAssimilated=");
	if (_contextMsgAssimilated!=null) {
	    str.append(_contextMsgAssimilated.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgAssimilatedTitle=");
	if (_contextMsgAssimilatedTitle!=null) {
	    str.append(_contextMsgAssimilatedTitle.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgAssimilate=");
	if (_contextMsgAssimilate!=null) {
	    str.append(_contextMsgAssimilate.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgAssimilateTitle=");
	if (_contextMsgAssimilateTitle!=null) {
	    str.append(_contextMsgAssimilateTitle.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgBirth=");
	if (_contextMsgBirth!=null) {
	    str.append(_contextMsgBirth.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgBirthTitle=");
	if (_contextMsgBirthTitle!=null) {
	    str.append(_contextMsgBirthTitle.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgDeath=");
	if (_contextMsgDeath!=null) {
	    str.append(_contextMsgDeath.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgDeathTitle=");
	if (_contextMsgDeathTitle!=null) {
	    str.append(_contextMsgDeathTitle.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgEnd=");
	if (_contextMsgEnd!=null) {
	    str.append(_contextMsgEnd.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgEndTitle=");
	if (_contextMsgEndTitle!=null) {
	    str.append(_contextMsgEndTitle.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgScare=");
	if (_contextMsgScare!=null) {
	    str.append(_contextMsgScare.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contextMsgScareTitle=");
	if (_contextMsgScareTitle!=null) {
	    str.append(_contextMsgScareTitle.toString());
	} else {
	    str.append("null");
	}
    
    str.append("}");

    return str.toString();
  }

}
