
package uk.ac.horizon.ug.exploding.client.model;
/** 
 * Identity element is ID.
 * 
 * Autogenerated by bean2java.xsl */
public class TimelineEvent 
{

  /** no-arg cons */
  public TimelineEvent()
  {
  }

  /* implements ., i.e. 
    uk.ac.horizon.ug.exploding.db.TimelineEvent */
  
  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _ID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getID()
  {
  
    return _ID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setID(java.lang.String ID)
  {
  
    this._ID = ID;
    
  }

  /** is set?
   */
  public boolean isSetID() {
    return this._ID != null; 
  }

  /** unset
   */
  public void unsetID()  {
    this._ID = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _orgId;
  
  /** getter - 
   */
  public java.lang.Integer getOrgId()
  {
  
    return _orgId;
    
  }

  /** setter - 
   */
  public void setOrgId(java.lang.Integer orgId)
  {
  
    this._orgId = orgId;
    
  }

  /** is set?
   */
  public boolean isSetOrgId() {
    return this._orgId != null; 
  }

  /** unset
   */
  public void unsetOrgId()  {
    this._orgId = null; 
  }

  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _contentGroupID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getContentGroupID()
  {
  
    return _contentGroupID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setContentGroupID(java.lang.String contentGroupID)
  {
  
    this._contentGroupID = contentGroupID;
    
  }

  /** is set?
   */
  public boolean isSetContentGroupID() {
    return this._contentGroupID != null; 
  }

  /** unset
   */
  public void unsetContentGroupID()  {
    this._contentGroupID = null; 
  }

  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _playerID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getPlayerID()
  {
  
    return _playerID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setPlayerID(java.lang.String playerID)
  {
  
    this._playerID = playerID;
    
  }

  /** is set?
   */
  public boolean isSetPlayerID() {
    return this._playerID != null; 
  }

  /** unset
   */
  public void unsetPlayerID()  {
    this._playerID = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _name;
  
  /** getter - 
   */
  public java.lang.String getName()
  {
  
    return _name;
    
  }

  /** setter - 
   */
  public void setName(java.lang.String name)
  {
  
    this._name = name;
    
  }

  /** is set?
   */
  public boolean isSetName() {
    return this._name != null; 
  }

  /** unset
   */
  public void unsetName()  {
    this._name = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _ref;
  
  /** getter - 
   */
  public java.lang.String getRef()
  {
  
    return _ref;
    
  }

  /** setter - 
   */
  public void setRef(java.lang.String ref)
  {
  
    this._ref = ref;
    
  }

  /** is set?
   */
  public boolean isSetRef() {
    return this._ref != null; 
  }

  /** unset
   */
  public void unsetRef()  {
    this._ref = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _description;
  
  /** getter - 
   */
  public java.lang.String getDescription()
  {
  
    return _description;
    
  }

  /** setter - 
   */
  public void setDescription(java.lang.String description)
  {
  
    this._description = description;
    
  }

  /** is set?
   */
  public boolean isSetDescription() {
    return this._description != null; 
  }

  /** unset
   */
  public void unsetDescription()  {
    this._description = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _zoneId;
  
  /** getter - 
   */
  public java.lang.Integer getZoneId()
  {
  
    return _zoneId;
    
  }

  /** setter - 
   */
  public void setZoneId(java.lang.Integer zoneId)
  {
  
    this._zoneId = zoneId;
    
  }

  /** is set?
   */
  public boolean isSetZoneId() {
    return this._zoneId != null; 
  }

  /** unset
   */
  public void unsetZoneId()  {
    this._zoneId = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _enabled;
  
  /** getter - 
   */
  public java.lang.Integer getEnabled()
  {
  
    return _enabled;
    
  }

  /** setter - 
   */
  public void setEnabled(java.lang.Integer enabled)
  {
  
    this._enabled = enabled;
    
  }

  /** is set?
   */
  public boolean isSetEnabled() {
    return this._enabled != null; 
  }

  /** unset
   */
  public void unsetEnabled()  {
    this._enabled = null; 
  }

  /** internal value - 
   */
  protected java.lang.Float _startTime;
  
  /** getter - 
   */
  public java.lang.Float getStartTime()
  {
  
    return _startTime;
    
  }

  /** setter - 
   */
  public void setStartTime(java.lang.Float startTime)
  {
  
    this._startTime = startTime;
    
  }

  /** is set?
   */
  public boolean isSetStartTime() {
    return this._startTime != null; 
  }

  /** unset
   */
  public void unsetStartTime()  {
    this._startTime = null; 
  }

  /** internal value - 
   */
  protected java.lang.Float _endTime;
  
  /** getter - 
   */
  public java.lang.Float getEndTime()
  {
  
    return _endTime;
    
  }

  /** setter - 
   */
  public void setEndTime(java.lang.Float endTime)
  {
  
    this._endTime = endTime;
    
  }

  /** is set?
   */
  public boolean isSetEndTime() {
    return this._endTime != null; 
  }

  /** unset
   */
  public void unsetEndTime()  {
    this._endTime = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _track;
  
  /** getter - 
   */
  public java.lang.Integer getTrack()
  {
  
    return _track;
    
  }

  /** setter - 
   */
  public void setTrack(java.lang.Integer track)
  {
  
    this._track = track;
    
  }

  /** is set?
   */
  public boolean isSetTrack() {
    return this._track != null; 
  }

  /** unset
   */
  public void unsetTrack()  {
    this._track = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _rgb;
  
  /** getter - 
   */
  public java.lang.Integer getRgb()
  {
  
    return _rgb;
    
  }

  /** setter - 
   */
  public void setRgb(java.lang.Integer rgb)
  {
  
    this._rgb = rgb;
    
  }

  /** is set?
   */
  public boolean isSetRgb() {
    return this._rgb != null; 
  }

  /** unset
   */
  public void unsetRgb()  {
    this._rgb = null; 
  }

  /* implements uk.ac.horizon.ug.exploding.db.StatsModifier.xml, i.e. 
    uk.ac.horizon.ug.exploding.db.StatsModifier */
  
  /** internal value - 
   */
  protected java.lang.Integer _health;
  
  /** getter - 
   */
  public java.lang.Integer getHealth()
  {
  
    return _health;
    
  }

  /** setter - 
   */
  public void setHealth(java.lang.Integer health)
  {
  
    this._health = health;
    
  }

  /** is set?
   */
  public boolean isSetHealth() {
    return this._health != null; 
  }

  /** unset
   */
  public void unsetHealth()  {
    this._health = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _healthMax;
  
  /** getter - 
   */
  public java.lang.Integer getHealthMax()
  {
  
    return _healthMax;
    
  }

  /** setter - 
   */
  public void setHealthMax(java.lang.Integer healthMax)
  {
  
    this._healthMax = healthMax;
    
  }

  /** is set?
   */
  public boolean isSetHealthMax() {
    return this._healthMax != null; 
  }

  /** unset
   */
  public void unsetHealthMax()  {
    this._healthMax = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _healthMin;
  
  /** getter - 
   */
  public java.lang.Integer getHealthMin()
  {
  
    return _healthMin;
    
  }

  /** setter - 
   */
  public void setHealthMin(java.lang.Integer healthMin)
  {
  
    this._healthMin = healthMin;
    
  }

  /** is set?
   */
  public boolean isSetHealthMin() {
    return this._healthMin != null; 
  }

  /** unset
   */
  public void unsetHealthMin()  {
    this._healthMin = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _wealth;
  
  /** getter - 
   */
  public java.lang.Integer getWealth()
  {
  
    return _wealth;
    
  }

  /** setter - 
   */
  public void setWealth(java.lang.Integer wealth)
  {
  
    this._wealth = wealth;
    
  }

  /** is set?
   */
  public boolean isSetWealth() {
    return this._wealth != null; 
  }

  /** unset
   */
  public void unsetWealth()  {
    this._wealth = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _wealthMax;
  
  /** getter - 
   */
  public java.lang.Integer getWealthMax()
  {
  
    return _wealthMax;
    
  }

  /** setter - 
   */
  public void setWealthMax(java.lang.Integer wealthMax)
  {
  
    this._wealthMax = wealthMax;
    
  }

  /** is set?
   */
  public boolean isSetWealthMax() {
    return this._wealthMax != null; 
  }

  /** unset
   */
  public void unsetWealthMax()  {
    this._wealthMax = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _wealthMin;
  
  /** getter - 
   */
  public java.lang.Integer getWealthMin()
  {
  
    return _wealthMin;
    
  }

  /** setter - 
   */
  public void setWealthMin(java.lang.Integer wealthMin)
  {
  
    this._wealthMin = wealthMin;
    
  }

  /** is set?
   */
  public boolean isSetWealthMin() {
    return this._wealthMin != null; 
  }

  /** unset
   */
  public void unsetWealthMin()  {
    this._wealthMin = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _brains;
  
  /** getter - 
   */
  public java.lang.Integer getBrains()
  {
  
    return _brains;
    
  }

  /** setter - 
   */
  public void setBrains(java.lang.Integer brains)
  {
  
    this._brains = brains;
    
  }

  /** is set?
   */
  public boolean isSetBrains() {
    return this._brains != null; 
  }

  /** unset
   */
  public void unsetBrains()  {
    this._brains = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _brainsMax;
  
  /** getter - 
   */
  public java.lang.Integer getBrainsMax()
  {
  
    return _brainsMax;
    
  }

  /** setter - 
   */
  public void setBrainsMax(java.lang.Integer brainsMax)
  {
  
    this._brainsMax = brainsMax;
    
  }

  /** is set?
   */
  public boolean isSetBrainsMax() {
    return this._brainsMax != null; 
  }

  /** unset
   */
  public void unsetBrainsMax()  {
    this._brainsMax = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _brainsMin;
  
  /** getter - 
   */
  public java.lang.Integer getBrainsMin()
  {
  
    return _brainsMin;
    
  }

  /** setter - 
   */
  public void setBrainsMin(java.lang.Integer brainsMin)
  {
  
    this._brainsMin = brainsMin;
    
  }

  /** is set?
   */
  public boolean isSetBrainsMin() {
    return this._brainsMin != null; 
  }

  /** unset
   */
  public void unsetBrainsMin()  {
    this._brainsMin = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _action;
  
  /** getter - 
   */
  public java.lang.Integer getAction()
  {
  
    return _action;
    
  }

  /** setter - 
   */
  public void setAction(java.lang.Integer action)
  {
  
    this._action = action;
    
  }

  /** is set?
   */
  public boolean isSetAction() {
    return this._action != null; 
  }

  /** unset
   */
  public void unsetAction()  {
    this._action = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _actionMax;
  
  /** getter - 
   */
  public java.lang.Integer getActionMax()
  {
  
    return _actionMax;
    
  }

  /** setter - 
   */
  public void setActionMax(java.lang.Integer actionMax)
  {
  
    this._actionMax = actionMax;
    
  }

  /** is set?
   */
  public boolean isSetActionMax() {
    return this._actionMax != null; 
  }

  /** unset
   */
  public void unsetActionMax()  {
    this._actionMax = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _actionMin;
  
  /** getter - 
   */
  public java.lang.Integer getActionMin()
  {
  
    return _actionMin;
    
  }

  /** setter - 
   */
  public void setActionMin(java.lang.Integer actionMin)
  {
  
    this._actionMin = actionMin;
    
  }

  /** is set?
   */
  public boolean isSetActionMin() {
    return this._actionMin != null; 
  }

  /** unset
   */
  public void unsetActionMin()  {
    this._actionMin = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _instant;
  
  /** getter - 
   */
  public java.lang.Integer getInstant()
  {
  
    return _instant;
    
  }

  /** setter - 
   */
  public void setInstant(java.lang.Integer instant)
  {
  
    this._instant = instant;
    
  }

  /** is set?
   */
  public boolean isSetInstant() {
    return this._instant != null; 
  }

  /** unset
   */
  public void unsetInstant()  {
    this._instant = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _flags;
  
  /** getter - 
   */
  public java.lang.Integer getFlags()
  {
  
    return _flags;
    
  }

  /** setter - 
   */
  public void setFlags(java.lang.Integer flags)
  {
  
    this._flags = flags;
    
  }

  /** is set?
   */
  public boolean isSetFlags() {
    return this._flags != null; 
  }

  /** unset
   */
  public void unsetFlags()  {
    this._flags = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _absolute;
  
  /** getter - 
   */
  public java.lang.Integer getAbsolute()
  {
  
    return _absolute;
    
  }

  /** setter - 
   */
  public void setAbsolute(java.lang.Integer absolute)
  {
  
    this._absolute = absolute;
    
  }

  /** is set?
   */
  public boolean isSetAbsolute() {
    return this._absolute != null; 
  }

  /** unset
   */
  public void unsetAbsolute()  {
    this._absolute = null; 
  }

  /** equals */
  public boolean equals(Object o) {
    if (o==null) return false;
    if (!(o instanceof TimelineEvent)) return false;
    TimelineEvent oo = (TimelineEvent)o;
      if (_ID!=oo._ID &&
        (_ID==null || oo._ID==null ||
         !_ID.equals(oo._ID)))
      return false;
    if (_orgId!=oo._orgId &&
        (_orgId==null || oo._orgId==null ||
         !_orgId.equals(oo._orgId)))
      return false;
    if (_contentGroupID!=oo._contentGroupID &&
        (_contentGroupID==null || oo._contentGroupID==null ||
         !_contentGroupID.equals(oo._contentGroupID)))
      return false;
    if (_playerID!=oo._playerID &&
        (_playerID==null || oo._playerID==null ||
         !_playerID.equals(oo._playerID)))
      return false;
    if (_name!=oo._name &&
        (_name==null || oo._name==null ||
         !_name.equals(oo._name)))
      return false;
    if (_ref!=oo._ref &&
        (_ref==null || oo._ref==null ||
         !_ref.equals(oo._ref)))
      return false;
    if (_description!=oo._description &&
        (_description==null || oo._description==null ||
         !_description.equals(oo._description)))
      return false;
    if (_zoneId!=oo._zoneId &&
        (_zoneId==null || oo._zoneId==null ||
         !_zoneId.equals(oo._zoneId)))
      return false;
    if (_enabled!=oo._enabled &&
        (_enabled==null || oo._enabled==null ||
         !_enabled.equals(oo._enabled)))
      return false;
    if (_startTime!=oo._startTime &&
        (_startTime==null || oo._startTime==null ||
         !_startTime.equals(oo._startTime)))
      return false;
    if (_endTime!=oo._endTime &&
        (_endTime==null || oo._endTime==null ||
         !_endTime.equals(oo._endTime)))
      return false;
    if (_track!=oo._track &&
        (_track==null || oo._track==null ||
         !_track.equals(oo._track)))
      return false;
    if (_rgb!=oo._rgb &&
        (_rgb==null || oo._rgb==null ||
         !_rgb.equals(oo._rgb)))
      return false;
    if (_health!=oo._health &&
        (_health==null || oo._health==null ||
         !_health.equals(oo._health)))
      return false;
    if (_healthMax!=oo._healthMax &&
        (_healthMax==null || oo._healthMax==null ||
         !_healthMax.equals(oo._healthMax)))
      return false;
    if (_healthMin!=oo._healthMin &&
        (_healthMin==null || oo._healthMin==null ||
         !_healthMin.equals(oo._healthMin)))
      return false;
    if (_wealth!=oo._wealth &&
        (_wealth==null || oo._wealth==null ||
         !_wealth.equals(oo._wealth)))
      return false;
    if (_wealthMax!=oo._wealthMax &&
        (_wealthMax==null || oo._wealthMax==null ||
         !_wealthMax.equals(oo._wealthMax)))
      return false;
    if (_wealthMin!=oo._wealthMin &&
        (_wealthMin==null || oo._wealthMin==null ||
         !_wealthMin.equals(oo._wealthMin)))
      return false;
    if (_brains!=oo._brains &&
        (_brains==null || oo._brains==null ||
         !_brains.equals(oo._brains)))
      return false;
    if (_brainsMax!=oo._brainsMax &&
        (_brainsMax==null || oo._brainsMax==null ||
         !_brainsMax.equals(oo._brainsMax)))
      return false;
    if (_brainsMin!=oo._brainsMin &&
        (_brainsMin==null || oo._brainsMin==null ||
         !_brainsMin.equals(oo._brainsMin)))
      return false;
    if (_action!=oo._action &&
        (_action==null || oo._action==null ||
         !_action.equals(oo._action)))
      return false;
    if (_actionMax!=oo._actionMax &&
        (_actionMax==null || oo._actionMax==null ||
         !_actionMax.equals(oo._actionMax)))
      return false;
    if (_actionMin!=oo._actionMin &&
        (_actionMin==null || oo._actionMin==null ||
         !_actionMin.equals(oo._actionMin)))
      return false;
    if (_instant!=oo._instant &&
        (_instant==null || oo._instant==null ||
         !_instant.equals(oo._instant)))
      return false;
    if (_flags!=oo._flags &&
        (_flags==null || oo._flags==null ||
         !_flags.equals(oo._flags)))
      return false;
    if (_absolute!=oo._absolute &&
        (_absolute==null || oo._absolute==null ||
         !_absolute.equals(oo._absolute)))
      return false;

    return true;
  }
  /** hashcode */
  public int hashCode() {
    int val = 0;
      if (_ID!=null) val = val ^ _ID.hashCode();
    if (_orgId!=null) val = val ^ _orgId.hashCode();
    if (_contentGroupID!=null) val = val ^ _contentGroupID.hashCode();
    if (_playerID!=null) val = val ^ _playerID.hashCode();
    if (_name!=null) val = val ^ _name.hashCode();
    if (_ref!=null) val = val ^ _ref.hashCode();
    if (_description!=null) val = val ^ _description.hashCode();
    if (_zoneId!=null) val = val ^ _zoneId.hashCode();
    if (_enabled!=null) val = val ^ _enabled.hashCode();
    if (_startTime!=null) val = val ^ _startTime.hashCode();
    if (_endTime!=null) val = val ^ _endTime.hashCode();
    if (_track!=null) val = val ^ _track.hashCode();
    if (_rgb!=null) val = val ^ _rgb.hashCode();
    if (_health!=null) val = val ^ _health.hashCode();
    if (_healthMax!=null) val = val ^ _healthMax.hashCode();
    if (_healthMin!=null) val = val ^ _healthMin.hashCode();
    if (_wealth!=null) val = val ^ _wealth.hashCode();
    if (_wealthMax!=null) val = val ^ _wealthMax.hashCode();
    if (_wealthMin!=null) val = val ^ _wealthMin.hashCode();
    if (_brains!=null) val = val ^ _brains.hashCode();
    if (_brainsMax!=null) val = val ^ _brainsMax.hashCode();
    if (_brainsMin!=null) val = val ^ _brainsMin.hashCode();
    if (_action!=null) val = val ^ _action.hashCode();
    if (_actionMax!=null) val = val ^ _actionMax.hashCode();
    if (_actionMin!=null) val = val ^ _actionMin.hashCode();
    if (_instant!=null) val = val ^ _instant.hashCode();
    if (_flags!=null) val = val ^ _flags.hashCode();
    if (_absolute!=null) val = val ^ _absolute.hashCode();

    return val;
  }
  /** tostring */
  public String toString() {
    StringBuilder str = new StringBuilder("TimelineEvent:");
    
    str.append("{");
    
    
	str.append("ID=");
	if (_ID!=null) {
	    str.append(_ID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("orgId=");
	if (_orgId!=null) {
	    str.append(_orgId.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contentGroupID=");
	if (_contentGroupID!=null) {
	    str.append(_contentGroupID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("playerID=");
	if (_playerID!=null) {
	    str.append(_playerID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("name=");
	if (_name!=null) {
	    str.append(_name.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("ref=");
	if (_ref!=null) {
	    str.append(_ref.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("description=");
	if (_description!=null) {
	    str.append(_description.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("zoneId=");
	if (_zoneId!=null) {
	    str.append(_zoneId.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("enabled=");
	if (_enabled!=null) {
	    str.append(_enabled.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("startTime=");
	if (_startTime!=null) {
	    str.append(_startTime.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("endTime=");
	if (_endTime!=null) {
	    str.append(_endTime.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("track=");
	if (_track!=null) {
	    str.append(_track.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("rgb=");
	if (_rgb!=null) {
	    str.append(_rgb.toString());
	} else {
	    str.append("null");
	}
    
    str.append("}");

    return str.toString();
  }

}
